### PR TITLE
Add container_context to github action

### PR DESCRIPTION
**Pull request by gibsondan**
- change the mutations to use the new API to generate from a YAML document
- add the container_context field with an example

### CODE REVIEW

**Comment by gibsondan** [comment]
Once we land this are there any steps that we need to take for it to start running on existing users of the Github action?

**Comment by rexledesma** [comment]
For my previous PRs, I've tested them by opening a PR in internal that uses the new github action from the PR branch:
- See https://github.com/dagster-io/dagster-cloud-cicd-action/pull/13 which was tested with https://github.com/dagster-io/internal/pull/1350

**Review by rexledesma — CHANGES_REQUESTED** [review]
Requesting changes until we have a test PR that tries the github action

**Comment by gibsondan** [comment]
@rexledesma these are pushing to dogfood from this branch and working, I think that may be sufficient? https://github.com/dagster-io/dagster-cloud-cicd-action/actions

**Review by rexledesma — APPROVED** [review]
ah yes - forgot only code previews was not being CI/CD'd here

**Pull request merged**
